import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePassengerListPDF = (flight, passengers) => {
  // Initialize PDF
  const doc = new jsPDF();

  // Helper function to format date
  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // Add Logo and Title
  doc.setFontSize(24);
  doc.setTextColor(26, 115, 232); // #1a73e8
  doc.text('SKYWINGS', 105, 20, { align: 'center' });

  doc.setFontSize(18);
  doc.setTextColor(0);
  doc.text('Passenger Manifest', 105, 30, { align: 'center' });

  // Flight Details
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Flight Details', 20, 45);
  doc.setFont(undefined, 'normal');
  doc.text(`Flight Number: ${flight.flightNumber}`, 20, 53);
  doc.text(`Route: ${flight.source} → ${flight.destination}`, 20, 61);
  doc.text(`Date Generated: ${formatDate(new Date())}`, 20, 69);

  // Stats Summary Box
  doc.setDrawColor(200);
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(20, 75, 170, 35, 3, 3, 'F');
  doc.setFont(undefined, 'bold');
  doc.text('Flight Statistics', 25, 83);
  doc.setFont(undefined, 'normal');
  
  const confirmedBookings = passengers.filter(p => p.status === 'confirmed').length;
  const totalRevenue = passengers.reduce((sum, p) => sum + p.totalAmount, 0);
  const occupancyRate = ((passengers.length / flight.totalSeats) * 100).toFixed(1);

  doc.text(`Total Passengers: ${passengers.length}`, 25, 91);
  doc.text(`Confirmed Bookings: ${confirmedBookings}`, 25, 99);
  doc.text(`Total Revenue: ₹${totalRevenue.toFixed(2)}`, 105, 91);
  doc.text(`Occupancy Rate: ${occupancyRate}%`, 105, 99);

  // Passenger List Table
  const tableData = passengers.map(passenger => [
    passenger.bookingId,
    {
      content: `${passenger.passenger.firstName} ${passenger.passenger.lastName}\n${passenger.passenger.gender} • ${formatDate(passenger.passenger.dateOfBirth)}`,
      styles: { cellWidth: 'auto' }
    },
    {
      content: `${passenger.passenger.email}\n${passenger.passenger.phone}`,
      styles: { cellWidth: 'auto' }
    },
    {
      content: passenger.seatNumber || 'Not assigned',
      styles: { halign: 'center' }
    },
    {
      content: passenger.status.toUpperCase(),
      styles: {
        halign: 'center',
        textColor: passenger.status === 'confirmed' ? [0, 128, 0] : // green
                  passenger.status === 'pending' ? [255, 150, 0] : // orange
                  [255, 0, 0] // red for cancelled
      }
    }
  ]);

  doc.autoTable({
    startY: 120,
    head: [['Booking ID', 'Passenger Details', 'Contact Information', 'Seat', 'Status']],
    body: tableData,
    theme: 'grid',
    styles: {
      fontSize: 10,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [26, 115, 232],
      textColor: 255,
      fontSize: 11,
      fontStyle: 'bold',
      halign: 'center'
    },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 50 },
      2: { cellWidth: 50 },
      3: { cellWidth: 25 },
      4: { cellWidth: 30 }
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128);
    
    // Add footer text
    doc.text('Generated by SKYWINGS Airline Management System', 105, 285, { align: 'center' });
    doc.text('This is an official document. Please handle with confidentiality.', 105, 290, { align: 'center' });
    
    // Add page numbers
    doc.text(`Page ${i} of ${pageCount}`, 105, 295, { align: 'center' });
  }

  // Save with dynamic filename
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`SKYWINGS_Passenger_List_${flight.flightNumber}_${timestamp}.pdf`);
};